export enum SYSTEM_ROLE {
  GUEST = "GUEST",
  VOLUNTEER = "VOLUNTEER",
  TEAM_LEAD = "TEAM_LEAD",
  PASTOR = "PASTOR",
  ADMIN = "ADMIN",
}

export enum EVENT_ROLE {
  ORGANIZER,
  TRANSITION,
  PREACHER,
  PROTOCOL,
  SERVICE_PRAYER,
  HAPPYLAND,
}
